export const metadata = {
  title: "Terms & Conditions — InsightCalculator",
  description: "Terms and conditions for using InsightCalculator calculators and tools.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-5xl px-4 py-16 lg:px-8">
      <h1 className="text-3xl font-semibold">Terms & Conditions</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last Updated: March 2026</p>

      <section className="mt-10 space-y-4">
        <h2 className="text-2xl font-semibold">1. Purpose of Use</h2>
        <p className="text-base text-muted-foreground leading-relaxed">
          By accessing and utilizing InsightCalculator, you agree to use our suite of tools for informational and illustrative purposes only. Our platform is designed to provide high-speed, high-utility data processing to assist in your workflow, but it does not constitute professional, financial, or legal advice.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="text-2xl font-semibold">2. Accuracy & "As-Is" Provision</h2>
        <p className="text-base text-muted-foreground leading-relaxed">
          We pride ourselves on precision-engineered logic and rigorous algorithmic testing. However, because variables and real-world conditions change, all results generated by our calculators are provided "as-is" and "as-available." These outputs are estimates meant to provide a "reality check" and should be verified against official documentation or professional consultation before making significant commitments.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="text-2xl font-semibold">3. Limitation of Liability</h2>
        <p className="text-base text-muted-foreground leading-relaxed">
          InsightCalculator, its developers, and its affiliates are not liable for any direct, indirect, or consequential losses—financial or otherwise—arising from the use of our platform. Users assume full responsibility for any decisions, investments, or technical implementations made based on the data provided by our tools.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="text-2xl font-semibold">4. Continuous Improvement</h2>
        <p className="text-base text-muted-foreground leading-relaxed">
          To maintain our standing as a top-tier infrastructure platform, we reserve the right to update, modify, or retire specific calculation tools at any time to improve site performance, SEO health, and mathematical accuracy.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="text-2xl font-semibold">Disclaimer</h2>
        <p className="text-base text-muted-foreground leading-relaxed">
          InsightCalculator is a utility provider, not a professional consultant. While we strive for 100% accuracy in our logic, users are encouraged to use the outputs as a starting point for their research rather than the final word. Decisions regarding salary negotiations, technical specifications, or financial planning should always be cross-referenced with certified experts.
        </p>
      </section>
    </div>
  );
}
